### PR TITLE
Design popup content with more than just a link to a Census Reporter page.

### PR DESCRIPTION
**Pull request by milafrerichs**
# Add more infos to the popup

Just added a few more infos into the popup. The infos that are available in the geojson. 
## Screenshot

bildschirmfoto 2015-04-04 um 20 30 53
## Discussion

What should we include? 
I would suggest the infos that are in the CensurReporter and the amounts from the API. 
Would suggest to use underscore. And find the data with it (filter, where). I would suggested underscore anyway since it will improve the performance and readability for the loops and so forth (issue #13 )

What do you think?

### CODE REVIEW

**Comment by milafrerichs** [comment]
the following needs to be included:
- [x] Demographics
- [x] number(survey result) that lead to the color

**Comment by milafrerichs** [comment]
Updated the popup a bit.
Styling would be next
bildschirmfoto 2015-10-28 um 20 55 08

**Comment by migurski** [comment]
This is great! Can you add per-capita income? The demographics should should match those in the corner buttons of the screenshot at https://github.com/codeforamerica/resident-web-use-research/issues/5.

**Comment by milafrerichs** [comment]
bildschirmfoto 2015-10-29 um 12 22 10

[Staging Preview](http://jekit.codeforamerica.org/milafrerichs/resident-web-use-research/4bfe59e7f4e897e6591a9b87552dec3af9fd1a4c/survey-page-results.html?gdoc=1QrizzwFTineFqjaTJ33HQTzdZklJMmJEBbYVaVfMeGU&cityname=Oakland%2C+CA)

**Comment by migurski** [comment]
I’m seeing `Uncaught ReferenceError: L is not defined(anonymous function) @ lib.js:485` in Chrome 43.

**Comment by milafrerichs** [comment]
Updated the library loading to not use a protocol. 
Jekit uses HTTPS by default and this caused a "Mixed Content" error.
Should be fixed now:
[Staging Preview](http://jekit.codeforamerica.org/milafrerichs/resident-web-use-research/0a6bc92ee9e549a3e898f96f434742c05f450f80/survey-page-results.html?gdoc=1QrizzwFTineFqjaTJ33HQTzdZklJMmJEBbYVaVfMeGU&cityname=Oakland%2C+CA)

**Comment by migurski** [comment]
Jekit’s not going to work here; Census reporter requests are blocked as insecure content.

**Comment by milafrerichs** [comment]
did a bit of polishing:
bildschirmfoto 2015-11-06 um 15 37 34

[Staging on AWS](http://cfa-reach-assessment.s3-website-us-east-1.amazonaws.com/survey-page-results.html?gdoc=1QrizzwFTineFqjaTJ33HQTzdZklJMmJEBbYVaVfMeGU&cityname=Oakland%2C+CA)
there are a few things to work on:
- [x] number formatting (thousand separator)
- [x] response text logic (text for none, response instead of responses for 1)
- [x] positioning tweaks
- [ ] color tweaks

**Comment by migurski** [comment]
These are looking excellent.

**Comment by milafrerichs** [comment]
bildschirmfoto 2015-11-10 um 15 23 03

**Comment by milafrerichs** [comment]
- [x] highlight the census tract: add border
- [x] popups should be visible at all times

**Comment by milafrerichs** [comment]
- [x] demographics button do not work correctly

**Pull request merged**
