### PR TITLE
Add Background and Label tileLayers

### PR DESCRIPTION
**Pull request by milafrerichs**
I assume you want the Label layer to be on top of the GeoJSON Layer?

This does not work yet. Have to do some more digging with the problems leaflet has with the ordering and z-index handling.

### CODE REVIEW

**Comment by migurski** [comment]
Hm, yeah—the reason to do it would be to get the labels showing. Maybe this is not yet possible in Leaflet?

**Comment by hamhands** [comment]
If memory serves, it's possible to sandwich data layers between tiles, but popups aren't possible. There might be a way around this by doing vector tiles in mapbox?

**Comment by milafrerichs** [comment]
ok got it. it is working now:
bildschirmfoto 2015-04-25 um 09 58 41
it's a bug in leaflet 0.7 and will be fixed in 1.0
this is a workaround from jfirebaugh
http://bl.ocks.org/jfirebaugh/5380413

**Comment by milafrerichs** [comment]
Here is a "staging" link.
Thanks to your jekit:
[Preview](http://jekit.codeforamerica.org/milafrerichs/resident-web-use-research/8f583b560ab0bf7bd1b07669f672cc88d8b749b5/survey-page-results.html?gdoc=1QrizzwFTineFqjaTJ33HQTzdZklJMmJEBbYVaVfMeGU&cityname=Oakland%2C+CA)

**Pull request merged**
